# Generated by Django 5.0.4 on 2024-06-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='No bio available', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_products',
            field=models.BooleanField(default=False),
        ),
    ]
