# Generated by Django 5.0.4 on 2024-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_view_products',
            field=models.BooleanField(default=False),
        ),
    ]
