# Generated by Django 5.0.4 on 2024-06-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_specification_product_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='SquareFeet',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Square Feet', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'draft')], default='in_review', max_length=10),
        ),
    ]
