# Generated by Django 5.0.6 on 2024-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_dtcp_approved_alter_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='map_latitude_longitude',
            field=models.CharField(blank=True, help_text='Enter latitude and longitude separated by a comma', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'draft'), ('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
    ]
