# Generated by Django 5.0.6 on 2024-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_map_latitude_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='map_latitude_longitude',
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Latitude in decimal degrees', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Longitude in decimal degrees', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'draft'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
    ]
