# Generated by Django 5.0.4 on 2024-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='CMDA_approved',
            field=models.BooleanField(default=False, help_text='Check if the product is CMDA approved'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'draft')], default='in_review', max_length=10),
        ),
    ]
