# Generated by Django 5.0.4 on 2024-06-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_cmda_approved_product_cmda_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('draft', 'draft'), ('published', 'Published'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
    ]
