# Generated by Django 5.0.4 on 2024-06-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_product_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled'), ('draft', 'draft')], default='in_review', max_length=10),
        ),
    ]
