# Generated by Django 5.0.4 on 2024-06-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_product_specification_remove_product_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('draft', 'draft'), ('published', 'Published'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
    ]
