# Generated by Django 5.0.4 on 2024-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_product_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('draft', 'draft'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published')], default='in_review', max_length=10),
        ),
    ]
